name: 'Publish Docker image to Docker Hub'

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: 'docker login -u huseyinorer -p ${{ secrets.DOCKER_HUB_PASSWORD }}'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag huseyinorer/skyhook:latest
    - name: Push the Docker image
      run: docker push huseyinorer/skyhook